# Generated by Django 3.1 on 2021-01-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210113_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',)},
        ),
    ]
